name: Update Credly Badges

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'  # Runs weekly

jobs:
  update-badges:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Update Credly Badges
        uses: ericnakagawa/credly-badges-action@latest
        with:
          CREDLY_USERNAME: mohamed-cherradi
          BADGE_COUNT: 10
          
      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git diff --quiet && git diff --staged --quiet || git commit -m "Update Credly badges"
          git push
